local lu = require('luaunit')

TestWindowsSort = require('tests/test_windows_sort')
TestSpacesModel = require('tests/test_spaces_model')
TestNativeSpace = require('tests/test_native_space')
TestEmulatedSpace = require('tests/test_emulated_space')
TestMoveWindowToVirtualSpace = require('tests/test_move_window_to_virtual_space')
TestTelemetry = require('tests/test_telemetry')
TestWindowCache = require('tests/test_window_cache')
TestSpaceWatcher = require('tests/test_space_watcher')
TestGetWindowsApi = require('tests/test_get_windows_api')
TestPublicApi = require('tests/test_public_api')
TestWindowDestroyed = require('tests/test_window_destroyed')

os.exit(lu.LuaUnit.run())
